/*
 * APIMATICCalculator.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10-05-2016
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using NUnit.Framework;
using APIMATICCalculator.PCL;
using APIMATICCalculator.PCL.Controllers;
 
using APIMATICCalculator.PCL.Models;
 
using APIMATICCalculator.PCL.Exceptions;
using APIMATICCalculator.PCL.Http.Client;
using APIMATICCalculator.Tests.Helpers;

namespace APIMATICCalculator.Tests
{
    [TestFixture]
    public class SimpleCalculatorControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static SimpleCalculatorController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().SimpleCalculator;
        }

        /// <summary>
        /// Test Case to see if Calculator works
        /// </summary>
        [Test]
        public async Task TestSummationTest() 
        {
            // Parameters for the API call
            GetCalculateInput input = new GetCalculateInput();
            input.Operation = OperationTypeEnumHelper.ParseString("SUM");
            input.X = 5;
            input.Y = 6;

            // Perform API call
            double result = 0;

            try
            {
                result = await controller.GetCalculateAsync(input);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

 
            Assert.AreEqual(
                    11.0, result, ASSERT_PRECISION,
                    "Response should match expected value");
        }

        /// <summary>
        /// Test Case to see if Calculator works
        /// </summary>
        [Test]
        public async Task TestMultiplicationTest() 
        {
            // Parameters for the API call
            GetCalculateInput input = new GetCalculateInput();
            input.Operation = OperationTypeEnumHelper.ParseString("MULTIPLY");
            input.X = 5;
            input.Y = 6;

            // Perform API call
            double result = 0;

            try
            {
                result = await controller.GetCalculateAsync(input);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test whether the captured response is as we expected
            Assert.IsNotNull(result, "Result should exist");

 
            Assert.AreEqual(
                    30.0, result, ASSERT_PRECISION,
                    "Response should match expected value");
        }

    }
}
